### PR TITLE
README.md: Add model compatibility list

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by davidebeatrici** [comment]
The models listed at https://github.com/odya/esphome-powmr-hybrid-inverter use the same dongle, but for some reason they are not mentioned in [its page](https://powmr.com/products/powmr-wifi-module-with-rs232-remote-monitoring-solution-wifi-vm):



I'm going to add them.

**Comment by davidebeatrici** [comment]
The `POW-HVM2.0H-12V` and `POW-HVM2.4H-24V` seem to be discontinued, I only found an archived page for the latter.

**Review by leodesigner — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Please note that, as I realized in odya/esphome-powmr-hybrid-inverter#9, support for the `POW-HVM5.5K-48V` is provided by a different dongle.

**Comment by Sledje** [comment]
David or Leo - I need some project help connecting my PowMr through some controller (Raspberry PI, ESP, Arduino) to an EV charger.  I can pay a nominal hourly fee.  Are either of you available and interested?

**Comment by davidebeatrici** [comment]
Could you provide us some info, such as brand and model, of the EV charger?

**Comment by Sledje** [comment]
Hello - I will get back to you.  Thank you

**Comment by manfredr74** [comment]
I am using the go-e homefix charger 11kWhttps://go-e.com/en/products/go-echarger-homefixIt sends many data via MQTT and is also controllable via MQTT.Thx   Manfred-- Manfred ReisnerCEO, Smart Mobility, System Safetye-mail: ***@***.***: +4368181113224ACTARON GmbHHauptstrasse 297441 PilgersdorfAustria
-------- Ursprüngliche Nachricht --------Von: Davide Beatrici ***@***.***> Datum: 18.02.24  19:50  (GMT+01:00) An: leodesigner/powmr_comm ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [leodesigner/powmr_comm] README.md: Add model compatibility list (PR #5) 
Could you provide us some info, such as brand and model, of the EV charger?

**Comment by manfredr74** [comment]
Hello,well the Solarinverter does not need to communicate with the wallbox - just data exchange via MQTT would be nice.A commonly used MQTT- Broker in the smart home domain is Mosquitto.Like all smart home devices the wallbox fully supports MQTT and is also controllable.Manfred-- Manfred ReisnerCEO, Smart Mobility, System Safetye-mail: ***@***.***: +4368181113224ACTARON GmbHHauptstrasse 297441 PilgersdorfAustria
-------- Ursprüngliche Nachricht --------Von: Sledje ***@***.***> Datum: 20.02.24  11:49  (GMT+01:00) An: leodesigner/powmr_comm ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [leodesigner/powmr_comm] README.md: Add model compatibility list (PR #5) 
Hello - I will get back to you.  Thank you



On Sun, Feb 18, 2024 at 1:50 PM Davide Beatrici ***@***.***>

wrote:

**Pull request merged**
